# Generated by Django 3.2.12 on 2023-08-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmail',
            name='user',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
    ]
